server:
  port:
    8083

#spring:
#  application:
#    name: order
#  datasource:
#    username: amigoscode
#    url: jdbc:postgresql://localhost:5432/order
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true

spring:
  application:
    name: order
  datasource:
    password: 'root'
    url: jdbc:mysql://localhost:3306/order
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

spring.output.ansi.enabled: ALWAYS
spring.kafka.producer.bootstrap-server: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.topic.name: order_topic


logging.pattern.console:  "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"