package com.cinema.backendvideo.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UploadVideoResponse {
    private String videoId;  //generated after saved video to db
    private String videoUrl; //autogenerated when we upload video to amazon S3
}
